# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raw_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='raw_data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eraw_data.proto\"\xa7\x01\n\x07rawdata\x12\r\n\x05key_1\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x61te_2\x18\x02 \x01(\t\x12\x0e\n\x06\x63ont_3\x18\x03 \x01(\t\x12\x0e\n\x06\x63ont_4\x18\x04 \x01(\t\x12\x0e\n\x06\x64isc_5\x18\x05 \x01(\t\x12\x0e\n\x06\x64isc_6\x18\x06 \x01(\t\x12\r\n\x05\x63\x61t_7\x18\x07 \x01(\t\x12\r\n\x05\x63\x61t_8\x18\x08 \x01(\t\x12\x0e\n\x06\x63ont_9\x18\t \x01(\t\x12\x0f\n\x07\x63ont_10\x18\n \x01(\tb\x06proto3')
)




_RAWDATA = _descriptor.Descriptor(
  name='rawdata',
  full_name='rawdata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_1', full_name='rawdata.key_1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_2', full_name='rawdata.date_2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cont_3', full_name='rawdata.cont_3', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cont_4', full_name='rawdata.cont_4', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disc_5', full_name='rawdata.disc_5', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disc_6', full_name='rawdata.disc_6', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cat_7', full_name='rawdata.cat_7', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cat_8', full_name='rawdata.cat_8', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cont_9', full_name='rawdata.cont_9', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cont_10', full_name='rawdata.cont_10', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=186,
)

DESCRIPTOR.message_types_by_name['rawdata'] = _RAWDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

rawdata = _reflection.GeneratedProtocolMessageType('rawdata', (_message.Message,), dict(
  DESCRIPTOR = _RAWDATA,
  __module__ = 'raw_data_pb2'
  # @@protoc_insertion_point(class_scope:rawdata)
  ))
_sym_db.RegisterMessage(rawdata)


# @@protoc_insertion_point(module_scope)
